package properties

import (
	"sync"

	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

// Resources represents a high-security type resource class for searching localized character strings, etc.
// This class was automatically generated by the StronglyTypedResourceBuilder class
// through a tool like ResGen or Visual Studio.
// To add or remove an associate, edit the .ResX file and run ResGen again
// with the /str option, or recreate the VS project.
type Resources struct {
	resourceMan     *message.Printer
	resourceCulture language.Tag
	once            sync.Once
}

var instance *Resources
var once sync.Once

// GetResources returns the cached ResourceManager instance used by this class.
func GetResources() *Resources {
	once.Do(func() {
		instance = &Resources{}
	})
	return instance
}

// ResourceManager returns the cached ResourceManager instance used by this class.
func (r *Resources) ResourceManager() *message.Printer {
	r.once.Do(func() {
		r.resourceMan = message.NewPrinter(language.English) // Default to English, change as needed
	})
	return r.resourceMan
}

// Culture gets or sets the CurrentUICulture of the current thread for all
// resource lookups using this strongly typed resource class.
func (r *Resources) Culture() language.Tag {
	return r.resourceCulture
}

// SetCulture sets the CurrentUICulture of the current thread for all
// resource lookups using this strongly typed resource class.
func (r *Resources) SetCulture(culture language.Tag) {
	r.resourceCulture = culture
	r.resourceMan = message.NewPrinter(culture)
}
